TimeTracker/TimeTracker/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from filebrowser.sites import site
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    path('viktor-root/', admin.site.urls),
    path('',include('Tracker.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('admin/filebrowser/', site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

TimeTracker/Tracker/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name="home"),
    path('signin/', views.signin, name="signin"),
    # path('back_to_home/', views.back_to_home, name="back_to_home"),
    path('signout/', views.signout, name="signout"),

    path('add_worker/', views.add_worker, name="add_worker"),
    path('change_worker/', views.change_worker, name="change_worker"),
    path('get_workers/', views.get_workers, name="get_workers"),
    path('block_worker/', views.block_worker, name="block_worker"),
    path('remove_worker/', views.remove_worker, name="remove_worker"),
    # path('change_avatar/', views.change_avatar, name="change_avatar"),
    path('remove_worker/', views.remove_worker, name="remove_worker"),

    path('add_project/', views.add_project, name="add_project"),
    path('project_detail/', views.project_detail, name="project_detail"),
    path('change_project/', views.change_project, name="change_project"),
    path('complet_project/', views.complet_project, name="complet_project"),
    path('open_project/', views.open_project, name="open_project"),
    path('remove_project/', views.remove_project, name="remove_project"),

    path('add_task/', views.add_task, name="add_task"),
    path('save_task/', views.save_task, name="save_task"),
    path('change_task/', views.change_task, name="change_task"),
    path('start_task/', views.start_task, name="start_task"),
    path('end_task/', views.end_task, name="end_task"),
    path('completed_task/', views.completed_task, name="completed_task"),
    path('open_task/', views.open_task, name="open_task"),
    path('active_tasks/', views.active_tasks, name="active_tasks"),
    path('remove_task/', views.remove_task, name="remove_task"),

    path('add_comment/', views.add_comment, name="add_comment"),
    path('show_comments/', views.show_comments, name="show_comments"),

    path('get_time_logs/', views.get_time_logs, name="get_time_logs"),
    path('show_time_logs/', views.show_time_logs, name="show_time_logs"),
    path('remove_time_log/', views.remove_time_log, name="remove_time_log"),

    path('get_messages/', views.get_messages, name="get_messages"),
    path('show_message/', views.show_message, name="show_message"),
    path('remove_message/', views.remove_message, name="remove_message"),
]

TimeTracker/Tracker/models.py
from django.db import models
from tinymce import HTMLField
from django.urls import reverse
from django_currentuser.db.models import CurrentUserField
from django.contrib.auth.models import User
from datetime import datetime, timedelta
import uuid


class Project(models.Model):

    project_name = models.CharField(max_length=256)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    summary = HTMLField('Summary')
    created_on = models.DateTimeField(auto_now_add=True)
    workers = models.ManyToManyField('Worker', help_text="Select a worker for this project", related_name='project_worker')
    is_completed = models.BooleanField(default=False)
    date_of_end = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ["-created_on", "is_completed"]

    def complete(self):
        self.created_on = datetime.now() - timedelta(days=7)
        self.date_of_end = datetime.now()
        self.is_completed = True
        self.save()

    def open(self):
        self.created_on = datetime.now()
        self.is_completed = False
        self.save()

    def __str__(self):
        return self.project_name


class Task(models.Model):

    title = models.CharField(max_length=200)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = CurrentUserField(editable=False)
    worker = models.ForeignKey('Worker', on_delete=models.SET_NULL, null=True, blank=True)
    description = HTMLField('Description')
    project = models.ForeignKey('Project', on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=False)
    is_completed = models.BooleanField(default=False)
    PRIORITIZE = (
        ('L', 'Low'),
        ('N', 'Normal'),
        ('H', 'High'),
        ('I', 'Important'),
        ('U', 'Urgent'),
    )
    priority_of_task = models.CharField(max_length=1, choices=PRIORITIZE, default='N')
    TYPES = (
        ('B', 'Bug'),
        ('F', 'Feature'),
        ('T', 'Task'),
        ('I', 'Improvement'),
    )
    type_of_task = models.CharField(max_length=1, choices=TYPES, default='T')
    date_of_start = models.DateTimeField(auto_now_add=True)
    date_of_end = models.DateTimeField(null=True, blank=True)
    available_from = models.DateField()
    available_to = models.DateField()
    is_available = models.BooleanField(default=False)
    estimated_time = models.CharField(max_length=10, default="24:00:00")
    spent_time = models.CharField(max_length=9, default="00:00:00")

    class Meta:
        ordering = ["-date_of_start", "is_completed"]

    def accessibility(self):
        today = datetime.now().date()
        if self.available_from <= today and self.available_to >= today:
            self.is_available = True
        else:
            self.is_available = False
        self.save()

    def complete(self):
        self.date_of_start = datetime.now() - timedelta(days=7)
        self.date_of_end = datetime.now()
        self.worker = None
        self.is_active = False
        self.is_completed = True
        self.save()

    def open(self):
        self.date_of_start = datetime.now()
        self.is_completed = False
        self.estimated_time = "24:00:00"
        self.spent_time = "00:00:00"
        self.save()

    def end(self):
        self.date_of_end = datetime.now()
        self.is_active = False
        self.worker = None
        self.save()

    def __str__(self):
        return self.title


class Comment(models.Model):

    task = models.ForeignKey('Task', on_delete=models.SET_NULL, null=True)
    comments = models.CharField(max_length=200)
    author = models.CharField(max_length=50)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]

class Worker(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    is_blocked = models.BooleanField(default=False)
    date_of_start = models.DateField(auto_now_add=True)
    POSTS = (
        ('1', 'Analyst'),
        ('2', 'Designer'),
        ('3', 'Developer'),
        ('4', 'Engineer'),
        ('5', 'Lead'),
        ('6', 'Manager'),
        ('7', 'Programmer'),
        ('8', 'Tester'),
    )
    post = models.CharField(max_length=1, choices=POSTS, default='3')
    avatar = models.ImageField(default="img/default.webp", blank=True, null=True, upload_to="avatars")

    class Meta:
        ordering = ["-date_of_start", "is_blocked"]

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    def full_name(self):
        return self.last_name + ' ' + self.first_name

    def block(self):
        self.is_blocked = True
        self.save()

    def unblock(self):
        self.is_blocked = False
        self.save()

class TimeLog(models.Model):

    time_of_start = models.DateTimeField(auto_now_add=True)
    action = models.CharField(max_length=256)
    worker = models.ForeignKey('Worker', on_delete=models.SET_NULL, null=True, blank=True)
    task = models.ForeignKey('Task', on_delete=models.SET_NULL, null=True, blank=True)
    comment = models.TextField()
    spent_time = models.CharField(max_length=10, null=True, blank=True)

    class Meta:
        ordering = ["-time_of_start"]

    def __str__(self):
        return self.action

class Message(models.Model):

    title = models.CharField(max_length=256)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    receiver = models.ForeignKey('Worker', on_delete=models.SET_NULL, null=True, blank=True)
    message = HTMLField('Message')
    status = models.CharField(max_length=10, default="new", null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def read(self):
        self.status = ""
        self.save()

TimeTracker/Tracker/forms.py
from django import forms
from .models import Project, Task, Worker
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

    username = forms.CharField(min_length=2, max_length=30,widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(min_length=8, max_length=30, widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class WorkerForm(forms.ModelForm):

    first_name = forms.CharField(min_length=2, max_length=30, widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(min_length=2, max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={'class' : 'picker-date', 'placeholder': 'Choose your birth date', 'data-position': 'bottom left', 'readonly': ''}))

    class Meta:
        model = Worker
        fields = ['last_name', 'first_name', 'date_of_birth', 'post']
        widgets = {
            'post': forms.Select(choices=Worker.POSTS,attrs={'class': 'form-control'})
        }

class ProjectForm(forms.ModelForm):

    project_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Project name'}))
    summary = forms.CharField(widget=forms.Textarea(attrs={'class': 'mceEditor'}))

    class Meta:
        model = Project
        fields = ['project_name', 'summary', 'workers']

class TaskForm(forms.ModelForm):

    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Task title'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'mceEditor'}))
    estimated_time = forms.CharField(min_length=8, max_length=9, widget=forms.TextInput(attrs={'placeholder': 'Estimated time', 'value': '10:00:00'}))
    available_from = forms.DateField(widget=forms.DateInput(attrs={'class' : 'picker-date', 'placeholder': 'Choose the start date', 'data-position': 'bottom left', 'readonly': ''}))
    available_to = forms.DateField(widget=forms.DateInput(attrs={'class' : 'picker-date', 'placeholder': 'Choose the end date', 'data-position': 'bottom left', 'readonly': ''}))

    class Meta:
        model = Task
        fields = ['title', 'description', 'priority_of_task', 'type_of_task', 'estimated_time', 'available_from', 'available_to']
        widgets = {
            'priority_of_task': forms.Select(choices=Task.PRIORITIZE,attrs={'class': 'form-control'}),
            'type_of_task': forms.Select(choices=Task.TYPES,attrs={'class': 'form-control'})
        }

TimeTracker/Tracker/templates/Tracker/home.html
{% extends 'index.html' %}



{% block navbar %}
<!-- header with navbar menu -->
<nav class="navbar navbar-light amber fixed-top lighten-4 mb-4">
  {% if user.is_authenticated %}
  <ul class="navbar-nav mr-auto nav-flex-icons m-1">
    <li class="nav-item avatar">
      <a href="{% url 'home' %}" class="nav-link rounded-circle block-center p-0 worker-avatar" title="back to home">
        <img src="{{ worker.avatar.url }}" class="img-responsive" id="avatar-small" alt="avatar small" height="35">
      </a>
    </li>
  </ul>
  <button class="navbar-toggler first-button" type="button" data-toggle="collapse" data-target="#navbar-top" aria-controls="navbar-top" aria-expanded="false" aria-label="Toggle navigation">
    <div class="animated-icon"><span></span><span></span><span></span></div>
  </button>
  {% endif %}
  <div class="collapse navbar-collapse" id="navbar-top">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item m-1 text-center">
        <a href="{% url 'home' %}" class="nav-link menu-link block-center p-1 worker-avatar" onclick="closeMenu()">
          <i class="fas fa-home mr-1"></i>Home</a>
      </li>
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1" id="account" onclick="closeMenu()">
          <i class="fas fa-user-circle mr-1"></i>Account</a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1" id="add-new-worker" onclick="closeMenu()">
          <i class="fas fa-user-plus mr-1"></i>Add new worker</a>
      </li>
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1" id="list-of-workers" onclick="closeMenu()">
          <i class="fas fa-users mr-1"></i>List of workers</a>
      </li>
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1" id="add-new-project" onclick="closeMenu()">
          <i class="fas fa-plus-square mr-1"></i>Create new project</a>
      </li>
      {% endif %}
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1" id="list-of-tasks" onclick="closeMenu()">
          <i class="fas fa-chart-line mr-1"></i>Active tasks</a>
      </li>
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1 show-timelogs" onclick="closeMenu()">
          <i class="fas fa-stopwatch mr-1"></i>Time logs</a>
      </li>
      <li class="nav-item m-1 text-center">
        <a class="nav-link menu-link block-center p-1" href="{% url 'signout' %}">
          <i class="fas fa-sign-out-alt mr-1"></i>Log Out</a>
      </li>
    </ul>
  </div>
  {% endif %}
</nav>
<!-- end header -->
{% endblock %}

{% block main_block %}
{% for project in projects_list %}
{% if project.is_completed == False %}
<div class="card m-1 border border-info project-card" id="{{ project.id }}">
  {% if worker in project.workers.all or user.is_superuser %}
  <div class="p-1 m-1 light-green jumbotron lighten-2 waves-effect waves-light block-center text-center row">
    <div class="p-1 project-detail font-weight-bold col-lg-8 brief col-xs-8" title="{{ project.project_name }}">
      {{ project.project_name }}
    </div>
    <div class="col-lg-2 col-xs-2 ml-auto block-center p-1 text-center">
      {% if user.is_superuser %}
      <i class="far fa-times-circle m-1 mr-2 text-center" title="close the project"></i>
      <i class="fas fa-edit m-1 mr-2 text-center" title="edit the project"></i>
      {% endif %}
      <i class="fas fa-lock-open m-1 text-center" title="available"></i>
    </div>
    <div class="col-lg-2 col-xs-2 block-center date ml-auto" title="created on">{{ project.created_on }}</div>
  </div>
  {% else %}
  <div class="p-1 m-1 orange lighten-2 waves-effect waves-light block-center text-center row">
    <div class="p-1 col-lg-8 col-xs-8 text-center" title="{{ project.project_name }}">{{ project.project_name }}</div>
    <div class="p-1 col-lg-2 col-xs-2 ml-auto text-center"><i class="fas fa-lock" title="unavailable"></i></div>
    <div class="col-lg-2 col-xs-2 block-center date ml-auto" title="created on">{{ project.created_on }}</div>
  </div>
  {% endif %}
  <div class="row p-1">
    <div class="col-lg-12 col-xs-12 text-left">
      Workers: {{ project.workers.all|join:", " }}
    </div>
  </div>
</div>
{% else %}
<div class="card m-1 border border-warning project-card" id="{{ project.id }}">
  <div class="p-1 m-1 teal lighten-4 waves-effect waves-light block-center text-center row">
    <div class="p-1 col-lg-8 col-xs-8 font-weight-bold" title="{{ project.project_name }}">
      {{ project.project_name }}
    </div>
    <div class="col-lg-2 col-xs-2 ml-auto block-center text-center">
      {% if user.is_superuser %}
      <i class="far fa-arrow-alt-circle-up m-1 mr-2 text-center" title="open the project again"></i>
      <i class="fas fa-trash-alt m-1 mr-2 text-center" title="to trash"></i>
      <i class="fas fa-lock-open m-1 text-center" title="available"></i>
      {% else %}
      <i class="fas fa-lock m-1 text-center" title="unavailable"></i>
      {% endif %}
    </div>
    <div class="col-lg-2 col-xs-2 block-center date ml-auto" title="end date">{{ project.date_of_end }}</div>
  </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

{% block paginator %}
<nav class="font-weight-bold d-flex m-3 justify-content-center" aria-label="Page navigation example">
  {% if projects_list.has_other_pages %}
  <ul class="pagination pagination-circle pg-blue justify-content-center">
    {% if projects_list.has_previous %}
    <li class="page-item"><a href="?page={{ projects_list.previous_page_number }}"><span class="page-link">&laquo;</span></a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
    {% endif %}
    {% for p in projects_list.paginator.page_range %}
    {% if projects_list.number == p %}
    <li class="page-item active"><span class="page-link" aria-hidden="true">{{ p }}<span class="sr-only">(current)</span></span></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
    {% endif %}
    {% endfor %}
    {% if projects_list.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{ projects_list.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
    {% endif %}
    {% endif %}
  </ul>
</nav>
{% endblock %}

TimeTracker/Tracker/templates/Tracker/login.html
{% extends 'index.html' %}



{% block main_block %}
<div class="card login-block p-3 m-0">
  <div class="login-dialog font-weight-bold p-1">
    <h5 class="card-header info-color white-text text-center py-4">
      Sign in
    </h5>
    <div class="jumbotron row px-1 mt-1 mb-1">
      <div class="p-1 col-lg-12 col-xs-12 block-center text-center">
        <form class="block-center welcome row" id="user-login-form" method="POST" action="">
          {% csrf_token %}
          <div class="md-form-group p-1 col-lg-12 col-xs-12 block-center text-center">
            <div class="row">
              <div class="md-form m-1 p-1 col-lg-12 col-xs-12">
                <input type="text" id="login-username" name="username" class="form-control rounded z-depth-3 white" minlength="2" maxlength="30" placeholder="Username" required>
              </div>
              <div class="md-form m-1 p-1 col-lg-12 col-xs-12">
                <input type="password" id="login-password" name="password" class="form-control rounded z-depth-3 white" minlength="8" maxlength="30" placeholder="Password" required>
              </div>
            </div>
          </div>
          <div class="p-1 m-1 col-lg-12 col-xs-12 text-center block-center error">
          </div>
          <div class="p-1 p-1 col-lg-12 col-xs-12 text-center block-center">
            <button class="btn btn-success btn-rounded btn-block brown-text w-50 font-weight-bold waves-effect rounded" type="submit">Sign in</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="p-1 block-center text-center mt-3">
    <p>Time tracking system. Copyright &copy;
      <script>
        document.write(new Date().getFullYear());
      </script>, Viktor Kozachok</p>
  </div>
  <div class=" text-center">
    <hr class="red font-weight-bold">
  </div>
</div>
{% endblock %}

TimeTracker/Tracker/templates/Tracker/project.html
<!-- project detail page -->
{% if worker in project.workers.all or user.is_superuser %}
<div class="jumbotron" id="{{ project.id }}">
  <div class="p-1 m-1 block-center text-center row">
    <div class="col-lg-11 col-xs-11 block-center text-center project-name">
      <h1 class="h1-responsive font-weight-bold">{{ project.project_name }}</h1>
    </div>
    <div class="col-lg-1 col-xs-1 mr-auto block-center text-center">
      {% if user.is_superuser %}
      <i class="fas fa-plus-circle m-1 mr-2 text-center" onclick="closeMenu()" title="add new task"></i>
      <i class="fas fa-edit m-1 text-center" title="edit the project"></i>
      {% endif %}
    </div>
  </div>
  <hr class="my-3">
  <div class="container-fluid z-depth-5 text-justify cyan lighten-5 p-3 m-auto project-summary">{{ project.summary|safe }}</div>
  <div class="p-1 mt-3 grey" id="task-content">
    {% for task in task_list %}
    {% if not task.is_completed %}
    <div class="p-1 m-3 white task" id="{{ task.id }}">
      <div class="block-center text-center row success-color-dark p-3 m-3">
        <div class="col-lg-7 col-xs-7 block-center font-weight-bold text-center waves-effect waves-light p-3 warning-color" data-toggle="collapse" data-target="#summary{{ task.id }}" title="{{ task.title }}">
          {{ task.title }}
        </div>
        <div class="col-lg-4 col-xs-4 mr-auto block-center p-1 text-center">
          {% if user.is_superuser %}
          <i class="far fa-window-close m-1 mr-2 text-center" title="close the task"></i>
          <i class="far fa-edit m-1 mr-2 text-center" title="edit the task"></i>
          {% endif %}
          {% if task.is_available == True %}
          <i class="fas fa-sync m-1 mr-2 text-center" title="load comments"></i>
          {% if task.is_active == False %}
          <i class="far fa-check-square m-1 mr-2 text-center" title="start working"></i>
          {% elif worker == task.worker %}
          <i class="far fa-pause-circle m-1 mr-2 text-center" title="finish working"></i>
          {% else %}
          <i class="fas fa-lock m-1 mr-2 text-center" title="active"></i>
          {% endif %}
          <i class="far fa-plus-square m-1 text-center" title="add comment"></i>
          {% else %}
          <h6 class="m-1 text-center">The task is unavailable</h6>
          {% endif %}
        </div>
        <div class="col-lg-1 col-xs-1 mr-auto block-center time text-center">
          <div class="row block-center">
            <div class="col-lg-12 col-xs-12 mb-3 text-center">
              <i class="fas fa-user-clock text-center mx-2" title="spent time"></i>{{ task.spent_time }}
            </div>
            <div class="col-lg-12 col-xs-12 mb-1 text-center">
              <i class="fas fa-business-time text-center mx-2" title="estimated time"></i>{{ task.estimated_time }}
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-xs-12 text-center p-1">
          <div id="summary{{ task.id }}" class="collapse">
            <div class="container-fluid grey lighten-2 p-1">
              <div class="block-center text-center row white m-1">
                {% if task.is_available == True %}
                <div class="col-lg-12 col-xs-12 summary-content text-justify p-3" contenteditable="true" id="content{{ task.id }}">{{ task.description|safe }}</div>
                <div class="col-lg-12 col-xs-12 m-1 p-1"><i class="fas fa-save m-1 text-center" title="save"></i></div>
                {% else %}
                <div class="col-lg-12 col-xs-12 summary-content text-justify p-3" id="content{{ task.id }}">{{ task.description|safe }}</div>
                {% endif %}
              </div>
              <div class="block-center text-center row orange accent-1">
                <div class="col-lg-4 col-xs-4 p-1 block-center text-center">Created: {{ task.date_of_start }}</div>
                <div class="col-lg-2 col-xs-2 p-1 block-center text-center">Priority: {{ task.get_priority_of_task_display }}</div>
                <div class="col-lg-2 col-xs-2 p-1 block-center text-center">Type: {{ task.get_type_of_task_display }}</div>
                {% if task.worker %}
                <div class="col-lg-4 col-xs-4 p-1 block-center text-center task_worker" id="task_worker{{ task.id }}">Worker: {{ task.worker }}</div>
                {% else %}
                <div class="col-lg-4 col-xs-4 p-1 block-center text-center task_worker" id="task_worker{{ task.id }}">Worker: the task is free</div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="block-center text-center row">
        <div class="col-lg-12 col-xs-12 block-center text-center warning-color m-1 p-1">
          Available from: {{ task.available_from }} to: {{ task.available_to }}
        </div>
      </div>
      {% if task.is_available == True %}
      <div class="silver border border-warning p-1 m-1" id="more{{ task.id }}">
        <h5>To load comments, just click on the sync button</h5>
      </div>
      {% endif %}
    </div>
    {% else %}
    <div class="p-1 m-3 white task" id="{{ task.id }}">
      <div class="block-center text-center row teal lighten-4 p-1 m-3">
        <div class="col-lg-12 text-center col-xs-12 p-1 unique-color">
          <div class="row p-1 mx-2">
            <div class="col-lg-11 col-xs-11 p-1 block-center font-weight-bold text-center waves-effect waves-light warning-color" data-toggle="collapse" data-target="#summary{{ task.id }}" title="{{ task.title }}">
              {{ task.title }}
            </div>
            <div class="col-lg-1 col-xs-1 p-1 block-center text-center">
              {% if user.is_superuser %}
              <i class="fas fa-arrow-alt-circle-up m-1 ml-2 mr-2 text-center" title="open the task again"></i>
              <i class="fas fa-trash m-1 text-center" title="to trash"></i>
              {% else %}
              <i class="far fa-calendar-check m-1 text-center"></i>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-xs-12 text-center p-1">
          <div id="summary{{ task.id }}" class="collapse">
            <div class="container-fluid grey lighten-2 p-1">
              <div class="block-center text-center row white m-1">
                <div class="col-lg-12 col-xs-12 summary-content text-justify p-3">{{ task.description|safe }}</div>
              </div>
              <div class="block-center text-center row orange accent-1">
                <div class="col-lg-12 col-xs-12 p-1 block-center text-center">End date: {{ task.date_of_end }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
    {% endfor %}
  </div>
</div>
{% endif %}